version: "3.9"

services:
  fhir-server:
    image: hapiproject/hapi:latest
    restart: unless-stopped
    container_name: test-hapi-search
    ports:
      - 8181:8080

    environment:
      - hapi.fhir.allow_multiple_delete=true
      - hapi.fhir.reuse_cached_search_results_millis=10000
      - hapi.fhir.cors.allow_Credentials=true
      - hapi.fhir.cors.allowed_origin_patterns="http:localhost:*"
      - hapi.fhir.fhir_version=R5
      - hapi.fhir.cr_enabled=true
      - hapi.fhir.enable_repository_validating_interceptor=false
      - hapi.fhir.auto_create_placeholder_reference_targets=true


      - spring.jpa.properties.hibernate.format_sql=false
      - spring.jpa.properties.hibernate.show_sql=false
      - spring.jpa.properties.hibernate.dialect=ca.uhn.fhir.jpa.model.dialect.HapiFhirH2Dialect
      - spring.jpa.properties.hibernate.search.enabled=true
      - spring.jpa.properties.hibernate.search.backend.type=lucene
#      - spring.jpa.properties.hibernate.search.backend.analysis.configurer=ca.uhn.fhir.jpa.search.HapiHSearchAnalysisConfigurers$$HapiLuceneAnalysisConfigurer
      - spring.jpa.properties.hibernate.search.backend.directory.type=local-filesystem
      - spring.jpa.properties.hibernate.search.backend.directory.root=target/lucenefiles
      - spring.jpa.properties.hibernate.search.backend.lucene_version=lucene_current
      - spring.batch.job.enabled=false
      - hapi.fhir.openapi_enabled=true
      - hapi.fhir.use_apache_address_strategy_https=true
      - hapi.fhir.allow_contains_searches=true
      - hapi.fhir.allow_override_default_search_params=true
      - hapi.fhir.cql_enabled=true
      - hapi.fhir.advanced_lucene_indexing=false
      - hapi.fhir.bulk_export_enabled=false
      - hapi.fhir.bulk_import_enabled=false
      - hapi.fhir.graphql_enabled=true
      - hapi.fhir.mdm_enabled=false
      - hapi.fhir.cors.allowed_origin='*'
      - hapi.fhir.ig_runtime_upload_enabled=true
      - hapi.fhir.custom_content_path=/custom
      - hapi.fhir.app_content_path=/apps


